Fix crash when parsing "c" tags
mskucherawy/OpenARC pull request #83
Opened 2018-04-16 14:58 UTC by flowerysong

["/" sig-c-tag-alg] is optional, and even if it weren't we shouldn't
crash when it's not present.

Fixes a segfault when arc_name_to_code() called strcasecmp() on NULL.

2018-05-04 18:38 UTC, mskucherawy requested changes

2018-05-04 18:38 UTC, mskucherawy commented on libopenarc/arc-canon.c
> +	if ( token == NULL )
No spaces around the comparison, please.

2018-05-04 18:38 UTC, mskucherawy commented on libopenarc/arc-canon.c
> +	    *body_canon = ARC_CANON_SIMPLE;
This should be tab-indented, just like the "else" block.

2018-05-04 19:10 UTC, flowerysong commented
Updated.

2018-05-23 19:46 UTC, mskucherawy approved these changes

2018-05-23 19:46 UTC, merged